import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://haejjfwuqlusmxyykpmo.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZWpqZnd1cWx1c214eXlrcG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzUzMjIxODMsImV4cCI6MTk5MDg5ODE4M30.OfZQU_ydvNsAYlMOTMVaQRssXYEWbNM0dH7z8Lp6UeE')