import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import Link from 'next/link';
import { supabase } from './../lib/supabaseClient';

const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  const [users, setUsers] = useState(0);
  const [growthRate, setGrowthRate] = useState(0);
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [company, setCompany] = useState('');
  const [score, setScore] = useState(0);
  const [color, setColor] = useState('');
  const [link, setLink] = useState('');
  const [hasSubmitted, setHasSubmitted] = useState(false);
  
  const getScore = async (u, g, n, e, c, co, l) => {
    const gRate = ((parseInt(u) - parseInt(g)) / (parseInt(g) + 1)) * 100;
    const score = (parseInt(u) * parseInt(gRate)) + parseInt(u);
    console.log(`${u} and ${g} Your score is: ${score}`);
    setScore(score);
    setHasSubmitted(true);
    await supabase.from('leaderboard').insert({ score: score, name: n, email: e, company: c, users: u, growthrate: g, color: co, link: l});
  }

  return (
    <>
      <Head>
        <title>flywheel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.description}>
          <p>
          🎡 flywheel
          </p>
          <Link href="/leaderboard">leaderboard</Link>
        </div>
        {hasSubmitted ? <div className={styles.formheadercontainer}>
          <h1>Your score: {score}</h1>
          <h2>Click <Link className={styles.leaderboardlink} href="/leaderboard">here</Link> to see if you beat your founder friends</h2>
        </div> : 
                <div className={styles.formcontainer}>
                <form className={styles.form}> 
       
                <label
                  >
                    name
                  </label>
                  <input
                  className={styles.box}
                  value={name}
                  placeholder= 'Farza'
                  type="text"
                  onChange={(e) => {
                    e.preventDefault();
                    setName(e.target.value);
                  }}
                  >
                  </input>
       
                  <label
                  >
                    email
                  </label>
                  <input
                  className={styles.box}
                  value={email}
                  placeholder= 'farza@buildspace.so'
                  type="text"
                  onChange={(e) => {
                    e.preventDefault();
                    setEmail(e.target.value);
                  }}
                  >
                  </input>
       
                  <label
                  >
                    company/project name
                  </label>
                  <input
                  className={styles.box}
                  value={company}
                  placeholder= 'buildspace'
                  type="text"
                  onChange={(e) => {
                    e.preventDefault();
                    setCompany(e.target.value);
                  }}
                  >
                  </input>
       
                <label
                  >
                    # of users right now (# you are tracking)
                  </label>
                  <input
                  className={styles.box}
                  value={users}
                  placeholder= {156}
                  type="number"
                  onChange={(e) => {
                    e.preventDefault();
                    setUsers(e.target.value);
                  }}
                  >
                  </input>
                
                  <label
                  >
                    # of users last week (roughly)
                  </label>
                  <input
                  className={styles.box}
                  value={growthRate}
                  placeholder={13}
                  type="number"
                  onChange={(e) => {
                    e.preventDefault();
                    setGrowthRate(e.target.value);
                  }}
                  >
                  </input>
       
                  <label
                  >
                   link to your project
                  </label>
                  <input
                  className={styles.box}
                  value={link}
                  placeholder= {'https://buildspace.so'}
                  type="text"
                  onChange={(e) => {
                    e.preventDefault();
                    setLink(e.target.value);
                  }}
                  >
                  </input>
       
                  <label
                  >
                   pick a color: 🟡 🔵 🟢 🔴
                  </label>
                  <input
                  className={styles.box}
                  value={color}
                  placeholder= {'yellow'}
                  type="text"
                  onChange={(e) => {
                    e.preventDefault();
                    setColor(e.target.value);
                  }}
                  >
                  </input>
       
       
                  <button className={styles.submitbutton} type="submit" onClick={(e) => {
                    e.preventDefault();
                    getScore(users, growthRate, name, email, company, color, link);
                  }}>
                    see if you are beating your friends
                  </button>
       
                </form>
               </div>
        }
{/* 
        <div className={styles.formcontainer}>
         <form className={styles.form}> 

         <label
           >
             name
           </label>
           <input
           value={name}
           placeholder= 'Farza'
           type="text"
           onChange={(e) => {
             e.preventDefault();
             setName(e.target.value);
           }}
           >
           </input>

           <label
           >
             email
           </label>
           <input
           value={email}
           placeholder= 'example@email.com'
           type="text"
           onChange={(e) => {
             e.preventDefault();
             setEmail(e.target.value);
           }}
           >
           </input>

           <label
           >
             company/project
           </label>
           <input
           value={company}
           placeholder= 'buildspace'
           type="text"
           onChange={(e) => {
             e.preventDefault();
             setCompany(e.target.value);
           }}
           >
           </input>

         <label
           >
             # users
           </label>
           <input
           value={users}
           placeholder= {156}
           type="number"
           onChange={(e) => {
             e.preventDefault();
             setUsers(e.target.value);
           }}
           >
           </input>
         
           <label
           >
             % weekly growth rate
           </label>
           <input
           value={growthRate}
           placeholder={13}
           type="number"
           onChange={(e) => {
             e.preventDefault();
             setGrowthRate(e.target.value);
           }}
           >
           </input>

           <label
           >
            link to your project
           </label>
           <input
           value={link}
           placeholder= {'https://buildspace.so'}
           type="text"
           onChange={(e) => {
             e.preventDefault();
             setLink(e.target.value);
           }}
           >
           </input>

           <label
           >
            your color
           </label>
           <input
           value={color}
           placeholder= {'yellow'}
           type="text"
           onChange={(e) => {
             e.preventDefault();
             setColor(e.target.value);
           }}
           >
           </input>


           <button type="submit" onClick={(e) => {
             e.preventDefault();
             getScore(users, growthRate, name, email, company, color, link);
           }}>
             get your score!
           </button>

         </form>
        </div> */}
      </main>
    </>
  )
}
